import type { Metadata } from "next";
import ClientProviders from "../_components/ClientProviders";
import Header from "../_components/header";

export const metadata: Metadata = {
  title: "FreshPack",
  description: "Generated by create next app",
};

export default function CartLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <ClientProviders>
        <Header />
        {children}
      </ClientProviders>
    </div>
  );
}
